-- CREATE TABLE IF NOT EXISTS apps (
--     pk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     id VARCHAR(256) UNIQUE,
--     title VARCHAR(256),
--     description VARCHAR(2000),
--     published_timestamp TIMESTAMP,
--     last_update_timestamp TIMESTAMP
-- );


CREATE TABLE IF NOT EXISTS ${TABLE_NAME} (
    pk INTEGER,
    id VARCHAR(256),
    title VARCHAR(256),
    description VARCHAR(2000),
    published_timestamp TIMESTAMP,
    last_update_timestamp TIMESTAMP,

  	PRIMARY KEY(pk),
    UNIQUE(id)
);